AWSTemplateFormatVersion: "2010-09-09"
Description: "PARAMETERS: Template where user can insert the name of the Bucket during creating stack"

Parameters:
    S3BucketName:
        Description: Enter S3 bucket name
        Type: String

        MinLength: 4
        #MaxLength: 6              #optional
        AllowedPattern: ^[a-zA-Z0-9]*$

Resources:
    S3Bucket:                        #logical id/name
        Type: AWS::S3::Bucket       #type of resource
        Properties:
            BucketName: !Ref S3BucketName        #reference on parameter - user type the name of bucket

Outputs:
    BucketName:
        Value: !Ref 'S3Bucket'   #output - show the name of S3 bucket 
